const fs = require('fs');

try {
  let content = fs.readFileSync('src/WallCalendar.tsx', 'utf8');

  // Strip types from WallCalendar.tsx using regex
  content = content.replace(/type\s+ThemeKey\s*=\s*(.*?);/s, '');
  content = content.replace(/interface\s+Theme\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/interface\s+MonthPalette\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/interface\s+MonthStyle\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/interface\s+DatePoint\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/interface\s+NotesStore\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/type\s+NoteMarker\s*=\s*(.*?);/s, '');
  content = content.replace(/interface\s+DayPreview\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/interface\s+CalendarCell\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/type\s+FlipStage\s*=\s*(.*?);/s, '');
  
  content = content.replace(/const\s+MONTHS\s*=\s*\[[\s\S]*?\]\s*as\s*const;/s, '');
  content = content.replace(/const\s+SHORT_MONTHS\s*=\s*\[[\s\S]*?\]\s*as\s*const;/s, '');
  content = content.replace(/const\s+HOLIDAYS\s*:\s*Record<string,\s*string>\s*=\s*\{[\s\S]*?\};/s, '');

  content = content.replace(/interface\s+StaticMonthSnapshot\s+\{[\s\S]*?\}/g, '');
  content = content.replace(/interface\s+NotesListItem\s+\{[\s\S]*?\}/g, '');

  // Strip multiple blank lines generated by removing the blocks
  content = content.replace(/\n\s*\n\s*\n/g, '\n\n');

  // Add the imports at the very top (after React imports)
  const importStatement = `import {\n  ThemeKey,\n  Theme,\n  MonthPalette,\n  MonthStyle,\n  DatePoint,\n  NotesStore,\n  NoteMarker,\n  DayPreview,\n  CalendarCell,\n  FlipStage,\n  StaticMonthSnapshot,\n  NotesListItem,\n  MONTHS,\n  SHORT_MONTHS,\n  HOLIDAYS\n} from './types';\n`;
  
  // Find first import and insert after react imports
  if (!content.includes('import { ThemeKey')) {
    content = content.replace(/(import .*?from 'react';\n|import React.*?;\n)/, `$1${importStatement}`);
  }

  fs.writeFileSync('src/WallCalendar.tsx', content);
  console.log("WallCalendar.tsx types stripped and imports added.");

} catch (e) {
  console.error("Failed to update file:", e);
}